In [15]:
import pandas as pd
df=pd.read_csv('/Users/Malavika/Downloads/Aiplane_BlueBook.csv.xls')
df.shape

(861, 22)

In [16]:
df.columns

Index(['Model', 'Company', 'Engine Type', 'HP or lbs thr ea engine',
       'Max speed Knots', 'Rcmnd cruise Knots', 'Stall Knots dirty',
       'Fuel gal/lbs', 'All eng service ceiling', 'Eng out service ceiling',
       'All eng rate of climb', 'Eng out rate of climb', 'Takeoff over 50ft',
       'Takeoff ground run', 'Landing over 50ft', 'Landing ground roll',
       'Gross weight lbs', 'Empty weight lbs', 'Length ft/in', 'Height ft/in',
       'Wing span ft/in', 'Range N.M.'],
      dtype='object')

In [17]:
df.index

RangeIndex(start=0, stop=861, step=1)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model                    861 non-null    object
 1   Company                  861 non-null    object
 2   Engine Type              834 non-null    object
 3   HP or lbs thr ea engine  834 non-null    object
 4   Max speed Knots          791 non-null    object
 5   Rcmnd cruise Knots       811 non-null    object
 6   Stall Knots dirty        735 non-null    object
 7   Fuel gal/lbs             807 non-null    float64
 8   All eng service ceiling  780 non-null    float64
 9   Eng out service ceiling  332 non-null    object
 10  All eng rate of climb    752 non-null    object
 11  Eng out rate of climb    358 non-null    object
 12  Takeoff over 50ft        712 non-null    float64
 13  Takeoff ground run       691 non-null    float64
 14  Landing over 50ft        712 non-null    float64
 15  Landing ground roll      660 non-null    float64
 16  Gross weight lbs         830 non-null    object
 17  Empty weight lbs         834 non-null    object
 18  Length ft/in             822 non-null    object
 19  Height ft/in             819 non-null    object
 20  Wing span ft/in          832 non-null    object
 21  Range N.M.               758 non-null    object
dtypes: float64(6), object(16)
memory usage: 148.1+ KB

In [19]:
df.head()

,Model,Company,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng service ceiling,Eng out service ceiling,...,Takeoff over 50ft,Takeoff ground run,Landing over 50ft,Landing ground roll,Gross weight lbs,Empty weight lbs,Length ft/in,Height ft/in,Wing span ft/in,Range N.M.
0,15 AC Sedan,Aeronca,Piston,145,104,91,46,36.0,13000.0,NaN,...,900.0,NaN,1300.0,NaN,2050,1180,25/3,10/3,37/5,370
1,11 CC Super Chief,Aeronca,Piston,85,89,83,44,15.0,12300.0,NaN,...,720.0,NaN,800.0,NaN,1350,820,20/7,8/9,36/1,190
2,7 CCM Champ,Aeronca,Piston,90,90,78,37,19.0,16000.0,NaN,...,475.0,NaN,850.0,NaN,1300,810,21/5,8/7,35/0,210
3,7 DC Champ,Aeronca,Piston,85,88,78,37,19.0,13000.0,NaN,...,500.0,NaN,850.0,NaN,1300,800,21/5,8/7,35/0,210
4,7 AC Champ,Aeronca,Piston,65,83,74,33,14.0,12500.0,NaN,...,632.0,NaN,885.0,NaN,1220,740,21/5,8/9,35/0,175

In [20]:
df.isnull().sum()

Model                        0
Company                      0
Engine Type                 27
HP or lbs thr ea engine     27
Max speed Knots             70
Rcmnd cruise Knots          50
Stall Knots dirty          126
Fuel gal/lbs                54
All eng service ceiling     81
Eng out service ceiling    529
All eng rate of climb      109
Eng out rate of climb      503
Takeoff over 50ft          149
Takeoff ground run         170
Landing over 50ft          149
Landing ground roll        201
Gross weight lbs            31
Empty weight lbs            27
Length ft/in                39
Height ft/in                42
Wing span ft/in             29
Range N.M.                 103
dtype: int64

In [21]:
df.drop(columns=["Eng out service ceiling","Eng out rate of climb"],inplace=True)

In [22]:
df.head()

,Model,Company,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng service ceiling,All eng rate of climb,Takeoff over 50ft,Takeoff ground run,Landing over 50ft,Landing ground roll,Gross weight lbs,Empty weight lbs,Length ft/in,Height ft/in,Wing span ft/in,Range N.M.
0,15 AC Sedan,Aeronca,Piston,145,104,91,46,36.0,13000.0,450,900.0,NaN,1300.0,NaN,2050,1180,25/3,10/3,37/5,370
1,11 CC Super Chief,Aeronca,Piston,85,89,83,44,15.0,12300.0,600,720.0,NaN,800.0,NaN,1350,820,20/7,8/9,36/1,190
2,7 CCM Champ,Aeronca,Piston,90,90,78,37,19.0,16000.0,650,475.0,NaN,850.0,NaN,1300,810,21/5,8/7,35/0,210
3,7 DC Champ,Aeronca,Piston,85,88,78,37,19.0,13000.0,620,500.0,NaN,850.0,NaN,1300,800,21/5,8/7,35/0,210
4,7 AC Champ,Aeronca,Piston,65,83,74,33,14.0,12500.0,370,632.0,NaN,885.0,NaN,1220,740,21/5,8/9,35/0,175

In [23]:
df.rename(columns={
    "Model": "Aircraft Model",
    "Company": "Manufacturer",
    "HP or lbs thr ea engine":"Engine Power Thrust", #power hb/thurst lb-- P (horsepower),lb (pounds of thrust)
    "Max speed Knots":"Max speed",
    "Rcmnd cruise Knots":"Cruise speed",
    "Stall Knots dirty":"Stall speed",
    "Fuel gal/lbs":"Fuel capacity",
    "All eng service ceiling":"Service ceiling",
    "All eng rate of climb":"Climb rate",
    "Takeoff over 50ft":"Takeoff distance",
    "Takeoff ground run":"Takeoff Run",
    "Landing over 50ft":"Landing Distance",
    "Landing ground roll":"Landing Run",
    "Gross weight lbs":"Gross Weight",
    "Empty weight lbs":"Empty Weight",
    "Length ft/in":"Aircraft Length",
    "Height ft/in":"Aircraft Height",
    "Wing span ft/in":"Wing Span",
    "Range N.M.":"Aircraft Range",
},inplace=True)

In [24]:
df.head()

,Aircraft Model,Manufacturer,Engine Type,Engine Power Thrust,Max speed,Cruise speed,Stall speed,Fuel capacity,Service ceiling,Climb rate,Takeoff distance,Takeoff Run,Landing Distance,Landing Run,Gross Weight,Empty Weight,Aircraft Length,Aircraft Height,Wing Span,Aircraft Range
0,15 AC Sedan,Aeronca,Piston,145,104,91,46,36.0,13000.0,450,900.0,NaN,1300.0,NaN,2050,1180,25/3,10/3,37/5,370
1,11 CC Super Chief,Aeronca,Piston,85,89,83,44,15.0,12300.0,600,720.0,NaN,800.0,NaN,1350,820,20/7,8/9,36/1,190
2,7 CCM Champ,Aeronca,Piston,90,90,78,37,19.0,16000.0,650,475.0,NaN,850.0,NaN,1300,810,21/5,8/7,35/0,210
3,7 DC Champ,Aeronca,Piston,85,88,78,37,19.0,13000.0,620,500.0,NaN,850.0,NaN,1300,800,21/5,8/7,35/0,210
4,7 AC Champ,Aeronca,Piston,65,83,74,33,14.0,12500.0,370,632.0,NaN,885.0,NaN,1220,740,21/5,8/9,35/0,175

In [25]:
df.isnull().sum()

Aircraft Model           0
Manufacturer             0
Engine Type             27
Engine Power Thrust     27
Max speed               70
Cruise speed            50
Stall speed            126
Fuel capacity           54
Service ceiling         81
Climb rate             109
Takeoff distance       149
Takeoff Run            170
Landing Distance       149
Landing Run            201
Gross Weight            31
Empty Weight            27
Aircraft Length         39
Aircraft Height         42
Wing Span               29
Aircraft Range         103
dtype: int64

In [26]:
df["Engine Type"].nunique()

9

In [28]:
df["Engine Type"].unique()

array(['Piston', 'Propjet', 'Jet', 'piston', 'Pistion', 'TSIO 520',
       'IO550', 'PT6A-35', 'PT6A-21', nan], dtype=object)

In [29]:
df["Engine Type"] = df["Engine Type"].replace({ "piston": "Piston", "Pistion": "Piston"})

In [30]:
df["Engine Type"].unique()

array(['Piston', 'Propjet', 'Jet', 'TSIO 520', 'IO550', 'PT6A-35',
       'PT6A-21', nan], dtype=object)

In [35]:
df["Engine Type"].mode()

0    Piston
Name: Engine Type, dtype: object

In [37]:
df["Engine Type"]=df["Engine Type"].fillna(df["Engine Type"].mode()[0])
df.isnull().sum()

Aircraft Model           0
Manufacturer             0
Engine Type              0
Engine Power Thrust     27
Max speed               70
Cruise speed            50
Stall speed            126
Fuel capacity           54
Service ceiling         81
Climb rate             109
Takeoff distance       149
Takeoff Run            170
Landing Distance       149
Landing Run            201
Gross Weight            31
Empty Weight            27
Aircraft Length         39
Aircraft Height         42
Wing Span               29
Aircraft Range         103
dtype: int64

In [34]:
df["Engine Power Thrust"].unique()

array(['145', '85', '90', '65', '350', '290', '680', '600', '525', '450',
       '300', '275', '245', '220', '100', '1295', '1050', '750', '180',
       '150', '115', '60', '160', '108', '800', '1200', '80', '2900',
       '2300', '850', '715', '550', '500', '380', '340', '295', '260',
       '325', '310', '285', '250', '240', '225', '205', '196', '185',
       '200', '165', '230', '190', '18920', '15125', '14750', '4600',
       '3700', '8729', '8650', '3500', '7500', '9220', '6826', '7323',
       '3850', '2950', '2850', '7665', '6400', '7034', '5907', '5770',
       '4000', '3991', '3650', '3786', '3400', '3045', '2887', '2500',
       '2820', '2490', '2400', '1965', '1900', '1350', '2200', '625',
       '375', '210', '675', '235', '175', '195', '110', '1846', '270',
       '265', '6722', '6402', '18500', '5000', '4750', '4500', '5918',
       '7000', '5200', '4125', '4250', '4315', '3230', '620', '579',
       '135', '81', '125', '700', '900', '7987', '7528', '6540', '7036',
       '3200', '1615', '400', '1000', '940wet', '1000 dry', '840', '665',
       '16900', '15144', '15385', '13850', '11400', '6040', '4420',
       '1950', '6900', '5225', '4300', '4660', '5525', '2965', '3750',
       '3360', '2050', '3100', '120', '3300', '3000', '967', '778', '727',
       '724', '776', '705', '605', '280', '217', '244', '720', '425',
       '112', '335', '305', '560', nan, '100 hp', '118', '820', '733',
       '748', '717.5', '435', '575'], dtype=object)